# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimmy Osma
email: josma109@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ingeniero de Sistemas, Geek, Desarrollador Web. Dando conocimiento al mundo, facilitando las comunicaciones y el entendimiento de los sistemas en la sociedad.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.redcoit.com" # the base hostname & protocol for your site
twitter_username: jimwy109
github_username:  jim109

# Build settings
markdown: kramdown
